---
title: "expression PCA"
author: "Meng"
date: "2024-05-22"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library("DESeq2")
library('RColorBrewer')
library("stringr")
library(VennDiagram)
library(rattle)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/"
```

## male leaf vs female leaf
```{r}
readcnt_leaf <- read.table(paste0(data,"rhastTXeQTLrna.txt"), header = T)
head(readcnt_leaf)

#remove 35aMLR (might be female), 40aF
col <- data.frame(colnames(readcnt_leaf))
readcnt_leaf <- readcnt_leaf[,-c(58,8)]

readcnt_leaf$all_mean <- rowMeans(readcnt_leaf[,c(7:159)])
readcnt_leaf <- readcnt_leaf %>% filter(all_mean >= 5) #19156


readcnt_matrix<-as.matrix(readcnt_leaf[ , -c(1:6,160)]) 
rownames(readcnt_matrix) <- readcnt_leaf[ , 1]
str(readcnt_matrix)
meta_data <- data.frame(colnames(readcnt_matrix))

colnames(meta_data) <- "id"
sex <- rep(NA, length(meta_data$id))
sex[grep("M", meta_data$id)] <- "male"
sex[grep("F", meta_data$id)] <- "female"
meta_data <- data.frame(meta_data, sex)
rownames(meta_data) <- meta_data[,1]
head(meta_data)
write.table(meta_data, file = paste0(data,"meta_data_sex.txt"), quote = F, row.names = F)
meta_data_sex <- read.table(paste0(data,"meta_data_sex.txt"), header = T)
```
simplify sample names
```{r}
colname <- colnames(readcnt_leaf)
write.table(colname, file = paste0(data, "colname.txt"), quote = F, row.names = F)
colname <- read.table(paste0(data, "colname.txt"))
colnames(readcnt_leaf) <- colname$V1
```


```{r}
dds <- DESeqDataSetFromMatrix(countData = readcnt_matrix, 
                              colData = meta_data,
                              design = ~ sex)
dds <- DESeq(dds)
resultsNames(dds) # "sex_male_vs_female"
res <- results(dds)
head(res)
summary(res)
result <- res[complete.cases(res),]
nrow(res) # 37659, 19156
nrow(result) # 24458, 19156
```
```{r}
normalized_countsl <- as.data.frame(counts(dds, normalized=T))
normalized_countsl <- normalized_countsl %>% mutate(gene=rownames(normalized_countsl)) 
normalized_countsl <- normalized_countsl[,c(156,1:155)]

col<-data.frame(colnames(normalized_countsl))
normalized_countsl <- normalized_countsl %>%  mutate(all_mean = rowMeans(normalized_countsl[,c(2:156)] )) 

cntl <- normalized_countsl %>% select(c(1,157))
cntl <- cntl %>% filter(all_mean >= 5)
```



```{r}
vsdata <- vst(dds, blind=FALSE)
p1 <- plotPCA(vsdata, intgroup=c("sex")) 

vsdata1 <- vst(dds_tissue, blind=FALSE)
p2 <- plotPCA(vsdata1, intgroup=c("tissue")) 

p1 + p2 + plot_layout(nrow = 2)
```

```{r} 
plotPCA(vsdata, intgroup=c("sex"))  + geom_text(aes(label=name),vjust=2)
```

DE genes
```{r}
DE_sex<-as.data.frame(result)
DE_sex <- DE_sex %>% mutate(gene = rownames(DE_sex))
DE_sex <- DE_sex[,c(7,1:6)]
head(DE_sex) 
DE_sex <- inner_join(DE_sex, gff, by = "gene")
write.table(DE_sex, file = paste0(data,"result_sex_cnt5.txt"), row.names = FALSE, quote = FALSE)
DE_sex <- read.table(paste0(data,"result_sex_cnt5.txt"), header = T)

DE_sex <- DE_sex %>% filter(chrom != "X" & chrom != "Y")

DE_sex_m <-  DE_sex %>% filter(log2FoldChange > 0 & padj < 0.05) # 2928
DE_sex_f <-  DE_sex %>% filter(log2FoldChange < 0 & padj < 0.05) # 2137

DE_sex_m <-  DE_sex %>% filter(log2FoldChange > 1 & padj < 0.05) # 977
DE_sex_f <-  DE_sex %>% filter(log2FoldChange < -1 & padj < 0.05) # 298
977+298

DE_sex_m <-  DE_sex %>% filter(log2FoldChange > 2 & padj < 0.05) # 657
DE_sex_f <-  DE_sex %>% filter(log2FoldChange < -2 & padj < 0.05) # 1


table(DE_sex_m$chrom_new)
table(DE_sex_f$chrom_new)

```

Venn
```{r}
DE_tissue <- inner_join(DE_tissue, gff, by = "gene")
DE_tissue <- read.table(paste0(data,"result_tissue_cnt5.txt"), header = T)

DE_tissue <- DE_tissue  %>% filter(chrom != "X" & chrom != "Y")
DE_tissue_pollen <- DE_tissue %>% filter(log2FoldChange > 0 & padj < 0.05) # 7567
DE_tissue_leaf <-  DE_tissue %>% filter(log2FoldChange < 0 & padj < 0.05) # 11445

v1<-DE_tissue_pollen$gene
v2<-DE_tissue_leaf$gene
v3<-DE_sex_f$gene
v4<-DE_sex_m$gene

venn.diagram(
  x = list(v1, v2, v3, v4),
  category.names = c("pollen-bias" , "leaf-bias" , "female-bias", "male-bias"),
  filename = '4venn_diagramm_p05_auto.png',
  output=TRUE,
  # Set names
  cat.cex = 1,
  cat.fontface = "bold")

```

```{r}
v1<-DE_tissue_pollen$gene
v2<-DE_tissue_leaf$gene
v3<-DE_sex_f$gene
v4<-DE_sex_m$gene

venn.diagram(
  x = list(v1, v2, v3, v4),
  category.names = c("pollen-bias" , "leaf-bias" , "female-bias", "male-bias"),
  filename = '4venn_diagramm_p05.png',
  output=TRUE,
  # Set names
  cat.cex = 1,
  cat.fontface = "bold")

write.table(v1, file = paste0(data, "pollen.txt"), row.names = F, quote = F, col.names = F)
write.table(v2, file = paste0(data, "leaf.txt"), row.names = F, quote = F, col.names = F)
write.table(v3, file = paste0(data, "f.txt"), row.names = F, quote = F, col.names = F)
write.table(v4, file = paste0(data, "m.txt"), row.names = F, quote = F, col.names = F)
```

## test
male female
all, 977, 298
pollen, 253, 52

male female
all, 1581, 466
pollen, 632, 60

male female
all, 1581, 466
leaf, 826, 389
```{r}
data <- matrix(c(1581, 632, 466, 60), nrow = 2, byrow = TRUE)

rownames(data) <- c("all", "pollen")
colnames(data) <- c("male", "female")

table_data <- as.table(data)

fisher.test(table_data)
```
```{r}
data <- matrix(c(1581, 826, 466, 389), nrow = 2, byrow = TRUE)

rownames(data) <- c("all", "leaf")
colnames(data) <- c("male", "female")

table_data <- as.table(data)

fisher.test(table_data)
```


```{r}
mosaicplot(table_data)
```

