---
title: "pollen and leaf expression"
author: "Meng"
date: "2024-05-21"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library("DESeq2")
library('RColorBrewer')
library("stringr")
library(VennDiagram)
library(rattle)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/"
```

deseq2 alerady run in phenotype_pl.Rmd
# pollen and leaf biased genes
DE genes

```{r}
DE_tissue <- read.table(paste0(data,"DE_tissue_full.txt"), header = T)
head(DE_tissue) 
DE_tissue <- DE_tissue %>% filter(padj<0.05) # 19822

results_pollen <- data.frame(chrom = unique(DE_tissue$chrom_new), log2FC_1 = NA, log2FC_2 = NA, log2FC_3 = NA)
results_leaf <- data.frame(chrom = unique(DE_tissue$chrom_new), log2FC_1 = NA, log2FC_2 = NA, log2FC_3 = NA)

log2_fold_changes <- c(0, 1, 2)
for (i in seq_along(log2_fold_changes)) {
  DE_tissue_pollen <- DE_tissue %>% filter(log2FoldChange > log2_fold_changes[i] & padj < 0.05)
  tablep <- as.data.frame(table(DE_tissue_pollen$chrom_new))
  results_pollen[1:7, paste0("log2FC_", i)] <- tablep[c(1:7), 2]  
  
  DE_tissue_leaf <- DE_tissue %>% filter(log2FoldChange < -log2_fold_changes[i] & padj < 0.05)
  tablel <- as.data.frame(table(DE_tissue_leaf$chrom_new))
  results_leaf[1:7, paste0("log2FC_", i)] <- tablel[c(1:7), 2]  
}
write.csv(results_pollen, paste0(data,"DE_pollen_cnt.csv"), row.names = FALSE)
write.csv(results_leaf, paste0(data,"DE_leaf_cnt.csv"), row.names = FALSE)
```



# enrichment on auto vs X vs Y vs PAR
## FC = 2
```{r}
DE_tissue_pollen <- DE_tissue %>% filter(log2FoldChange > 1 & padj < 0.05) # 6702
DE_tissue_leaf <-  DE_tissue %>% filter(log2FoldChange < -1 & padj < 0.05) # 9947

tablep <- as.data.frame(table(DE_tissue_pollen$chrom_new))
sum(tablep[c(1:4),2]) # 5135

tablel <- as.data.frame(table(DE_tissue_leaf$chrom_new))
sum(tablel[c(1:4),2]) # 7695

colnames(tablep) <- c("chrom", "pollen")
colnames(tablel) <- c("chrom", "leaf")
table <- inner_join(tablep, tablel, by = "chrom")

table <- table %>% add_row(chrom = "A", pollen = 5135, leaf = 7695)
write.table(table, file = paste0(data,"tablepl_P05_FC2.txt"), row.names = FALSE, quote = FALSE)
```

```{r}
table <- read.table(paste0(data,"tablepl_P05_FC2.txt"), header = T)
table_final <- table[c(5:8),]
table_long <- gather(table_final, lifestage, count, pollen : leaf, factor_key = TRUE)
write.table(table_long, file = paste0(data,"table_long.txt"), row.names = FALSE, quote = FALSE)
levels(table_long$lifestage) <- c("gametophyte-bias","sporophyte-bias")
table_long$lifestage <- factor(table_long$lifestage, level=c("sporophyte-bias","gametophyte-bias"))

hcols <- c("black",  "white")

p1 <- ggplot(table_long) +
geom_col(aes(x = chrom, y = count, fill = lifestage), position = "fill", colour ="black")  + xlab("") + ylab("Proportion of DE genes") + theme_light() + scale_fill_manual(values = hcols) + theme(axis.text=element_text(size=10), axis.title=element_text(size=10)) + ggtitle("a")

p2 <- ggplot(table_long) +geom_col(aes(x = chrom, y = count, fill = lifestage), colour ="black")  + xlab("") + ylab("Number of DE genes") + theme_light() + scale_fill_manual(values = hcols) + theme(axis.text=element_text(size=10), axis.title=element_text(size=10)) + ggtitle("b")

```

## FC = 4
```{r}
DE_tissue_pollen <- DE_tissue %>% filter(log2FoldChange > 2 & padj < 0.05) # 6702
DE_tissue_leaf <-  DE_tissue %>% filter(log2FoldChange < -2 & padj < 0.05) # 9947

tablep <- as.data.frame(table(DE_tissue_pollen$chrom_new))
sum(tablep[c(1:4),2]) # 3990

tablel <- as.data.frame(table(DE_tissue_leaf$chrom_new))
sum(tablel[c(1:4),2]) # 4887

colnames(tablep) <- c("chrom", "pollen")
colnames(tablel) <- c("chrom", "leaf")
table <- inner_join(tablep, tablel, by = "chrom")

table <- table %>% add_row(chrom = "A", pollen = 3990, leaf = 4887)
write.table(table, file = paste0(data,"tablepl_P05_FC4.txt"), row.names = FALSE, quote = FALSE)
```

```{r}
table <- read.table(paste0(data,"tablepl_P05_FC4.txt"), header = T)
table_final <- table[c(5:8),]
table_long <- gather(table_final, lifestage, count, pollen : leaf, factor_key = TRUE)
write.table(table_long, file = paste0(data,"table_long.txt"), row.names = FALSE, quote = FALSE)
levels(table_long$lifestage) <- c("gametophyte-bias","sporophyte-bias")
table_long$lifestage <- factor(table_long$lifestage, level=c("sporophyte-bias","gametophyte-bias"))

hcols <- c("black",  "white")

p3 <- ggplot(table_long) +
geom_col(aes(x = chrom, y = count, fill = lifestage), position = "fill", colour ="black")  + xlab("") + ylab("Proportion of DE genes") + theme_light() + scale_fill_manual(values = hcols) + theme(axis.text=element_text(size=10), axis.title=element_text(size=10)) + ggtitle("c")

p4 <- ggplot(table_long) +geom_col(aes(x = chrom, y = count, fill = lifestage), colour ="black")  + xlab("") + ylab("Number of DE genes") + theme_light() + scale_fill_manual(values = hcols) + theme(axis.text=element_text(size=10), axis.title=element_text(size=10)) + ggtitle("d")
```

```{r}
p1 + p2 + p3 + p4 + plot_layout(nrow = 2, guides = 'collect')
```


# contigency test
```{r}
table <- read.table(paste0(data,"tablepl_P05_FC4.txt"), header = T)
table <- read.table(paste0(data,"tablepl_P05_FC2.txt"), header = T)

table_final <- table[c(5:8),]
row.names(table_final) <- table_final[,1]
head(table_final)
```
Y vs A
```{r}
table_test <- table_final[c(3:4),c(2:3)]
head(table_test)
chisq.test(table_test)
fisher.test(table_test)
```

X vs Y
```{r}
table_test <- table_final[c(2,3),c(2:3)]
head(table_test)
chisq.test(table_test)
fisher.test(table_test)
```

PAR vs Y
```{r}
table_test <- table_final[c(1,3),c(2:3)]
head(table_test)
chisq.test(table_test)
fisher.test(table_test)
```



