---
title: "FL X and PAR"
author: "Meng"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
library(arrow)
library(dplyr)
library(ggplot2)
library(patchwork)
library(qvalue)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/eqtl/"
```


# PAR, X
```{r}
FL_PAR <- read.table(paste0(data, "FL_PAR.cis_qtl.txt"), header = T) # 1090
FL_X <- read.table(paste0(data, "FL_X.cis_qtl.txt"), header = T) # 1870

hist(FL_PAR$pval_beta, nclass = 20)
hist(FL_X$pval_beta, nclass = 20)

# qval_ML <- qvalue(FL_PAR$pval_beta)
# qval_FL <- qvalue(FL_X$pval_beta)
# summary(qval_ML)
# p1 <- hist(qval_ML)

```


```{r}
FL_PAR_eqtl <- read_parquet(paste0(data,"FL_PAR.cis_qtl_pairs.6.parquet"))
FL_PAR_eqtl_full <- inner_join(FL_PAR_eqtl, FL_PAR[,c(1,16:19)], by = "phenotype_id") # 81368
FL_PAR_eqtl_sig <- FL_PAR_eqtl_full %>% filter(pval_nominal < pval_nominal_threshold) # 738
FL_PAR_eqtl_sig <-FL_PAR_eqtl_sig %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))

FL_X_eqtl <- read_parquet(paste0(data,"FL_X.cis_qtl_pairs.5.parquet"))
FL_X_eqtl_full <- inner_join(FL_X_eqtl, FL_X[,c(1,16:19)], by = "phenotype_id") # 261175
FL_X_eqtl_sig <- FL_X_eqtl_full %>% filter(pval_nominal < pval_nominal_threshold) # 16282
FL_X_eqtl_sig <-FL_X_eqtl_sig %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))
```


```{r}
set.seed(13)
ML_eqtl_sig_min <- ML_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  filter(pval_nominal == min(pval_nominal)) %>% 
  slice_sample(n = 1) # 2421

set.seed(123)
MP_eqtl_sig_random <- MP_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  slice_sample(n = 1)  # 1475

```


```{r}
FL_eqtl_sig_min <- FL_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  filter(pval_nominal == min(pval_nominal)) # 3393
FL_eqtl_sig_min_af <- FL_eqtl_sig_min %>% dplyr::select(variant_id, af, maf) %>% distinct()

FL_PAR_sig_min <- FL_PAR_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  filter(pval_nominal == min(pval_nominal)) # 198

FL_PAR_sig_min_af <- FL_PAR_sig_min %>% dplyr::select(variant_id, af, maf) %>% distinct()


FL_X_sig_min <- FL_X_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  filter(pval_nominal == min(pval_nominal)) # 1644

FL_X_sig_min_af <- FL_X_sig_min %>% dplyr::select(variant_id, af, maf) %>% distinct()
```

```{r}
median(FL_eqtl_sig_min_af$maf)
median(FL_PAR_sig_min_af$maf)
median(FL_X_sig_min_af$maf)


```

```{r}
wilcox.test(FL_eqtl_sig_min_af$maf, FL_PAR_sig_min_af$maf)
wilcox.test(FL_eqtl_sig_min_af$maf, FL_X_sig_min_af$maf)
wilcox.test(FL_PAR_sig_min_af$maf, FL_X_sig_min_af$maf)
```

```{r}
# A
p<-ggplot(FL_eqtl_sig_min_af, aes(x=maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y)

p1 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("Female leaf - A")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10)) + ylim(0, 0.177)+ geom_vline(xintercept=0.1190475, color = "red",linetype="dashed")

# PAR
p<-ggplot(FL_PAR_sig_min_af, aes(x=maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y)

p2 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("Female leaf - PAR")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10)) + ylim(0, 0.177)+ geom_vline(xintercept=0.1, color = "red",linetype="dashed")

# X
p<-ggplot(FL_X_sig_min_af, aes(x=maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y)


p3 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("Female leaf - X")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10)) + ylim(0, 0.177)+ geom_vline(xintercept=0.1060606, color = "red",linetype="dashed")

p1 + p2 + p3
```



## write output
```{r}

```

