---
title: "interaction and MAF"
author: "Meng"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
library(arrow)
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyr)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/sex/"
padjust_bh <- function(p, fdr_threshold = 0.1) {
  if (any(!is.finite(p))) {
    stop('P values must be finite.')
  }
  n <- length(p)
  i <- n:1
  o <- order(p, decreasing = TRUE)
  ro <- order(o)
  adjusted_p <- pmin(1, cummin(n / i * p[o]))[ro]
  
  return(adjusted_p)
}

```


# all gene-variant pairs with interaction term
without sex as a covariate
```{r}
sex_interaction_A1 <- read_parquet(paste0(data,"nosex_inter.cis_qtl_pairs.1.parquet"))
sex_interaction_A2 <- read_parquet(paste0(data,"nosex_inter.cis_qtl_pairs.2.parquet"))
sex_interaction_A3 <- read_parquet(paste0(data,"nosex_inter.cis_qtl_pairs.3.parquet"))
sex_interaction_A4 <- read_parquet(paste0(data,"nosex_inter.cis_qtl_pairs.4.parquet"))
colnames(sex_interaction_A4)

sex_inter <- rbind(sex_interaction_A1, sex_interaction_A2, sex_interaction_A3, sex_interaction_A4) # 1083706
colnames(sex_inter)
```

```{r}
sex_inter$pval_gi_adj <- padjust_bh(sex_inter$pval_gi, fdr_threshold = 0.1)
sex_inter$pval_i_adj <- padjust_bh(sex_inter$pval_i, fdr_threshold = 0.1)
sex_inter$pval_g_adj <- padjust_bh(sex_inter$pval_g, fdr_threshold = 0.1)

gi_adj_01 <- sex_inter %>% filter(pval_gi_adj < 0.1) # 96
g_adj_01 <- sex_inter %>% filter(pval_g_adj < 0.1) # 1293
i_adj_01 <- sex_inter %>% filter(pval_i_adj < 0.1) # 119964

gi_adj_01_min <- gi_adj_01 %>%
  group_by(phenotype_id) %>% 
  filter(pval_gi_adj == min(pval_gi_adj)) # 13

g_adj_01_min <- g_adj_01 %>%
  group_by(phenotype_id) %>% 
  filter(pval_g_adj == min(pval_g_adj)) # 230

i_adj_01_min <- i_adj_01 %>%
  group_by(phenotype_id) %>% 
  filter(pval_i_adj == min(pval_i_adj)) # 3982

```


# top association for each phenotype sex_inter_top
```{r}
sex_inter_top <- read.table(paste0(data, "nosex_inter.cis_qtl_top_assoc.txt"), header = T) # 14587
colnames(sex_inter_top)
length(unique(sex_inter_top$phenotype_id)) 


sex_inter_top$pval_gi_adj <- padjust_bh(sex_inter_top$pval_gi, fdr_threshold = 0.1)
sex_inter_top$pval_i_adj <- padjust_bh(sex_inter_top$pval_i, fdr_threshold = 0.1)
sex_inter_top$pval_g_adj <- padjust_bh(sex_inter_top$pval_g, fdr_threshold = 0.1)

#pval_adj_bh <- sex_inter_top %>% filter(pval_adj_bh < 0.1) # 5

p_gi_adj_01 <- sex_inter_top %>% filter(pval_gi_adj < 0.1) # 9253, 9374
p_g_adj_01 <- sex_inter_top %>% filter(pval_g_adj < 0.1) # 7353, 7442
p_i_adj_01 <- sex_inter_top %>% filter(pval_i_adj < 0.1) # 0, 3339

p_gi_adj_005 <- sex_inter_top %>% filter(pval_gi_adj < 0.05) # 436
p_g_adj_005 <- sex_inter_top %>% filter(pval_g_adj < 0.05) # 2985
p_i_adj_005 <- sex_inter_top %>% filter(pval_i_adj < 0.05) # 2222

write.table(p_gi_adj_01$variant_id, file = paste0(data, "p_gi_adj_01.txt"), row.names = F, quote = F, col.names = F)
write.table(p_g_adj_01$variant_id, file = paste0(data, "p_g_adj_01.txt"), row.names = F, quote = F, col.names = F)
write.table(p_i_adj_01$variant_id, file = paste0(data, "p_i_adj_01.txt"), row.names = F, quote = F, col.names = F)

write.table(p_gi_adj_005$variant_id, file = paste0(data, "p_gi_adj_005.txt"), row.names = F, quote = F, col.names = F)
write.table(p_g_adj_005$variant_id, file = paste0(data, "p_g_adj_005.txt"), row.names = F, quote = F, col.names = F)
write.table(p_i_adj_005$variant_id, file = paste0(data, "p_i_adj_005.txt"), row.names = F, quote = F, col.names = F)

pval_adj_bh <- sex_inter_top %>% filter(pval_adj_bh < 0.1) # 5
write.csv(pval_adj_bh, file = paste0(data, "sex_interaction_padj_bh01.csv"), row.names = F, quote = F)
```

227 2723
```{r}
g <- p_g_adj_01 %>% select(variant_id, af) %>% distinct() # 2950, 7273, 7551
gi <- p_gi_adj_01 %>% select(variant_id, af)  %>% distinct() # 233, 9163, 9370


no_interaction <-  g %>%
  anti_join(gi, by = "variant_id") # 621

#interaction <- inner_join(g, gi, by = c("variant_id","af")) # 241
interaction <-  gi

interaction <- interaction %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))
no_interaction <- no_interaction %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))

p <-ggplot(interaction, aes(x=maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y)
p7 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("Pollen")+ labs(x="MAF", y="Proportion", title="G x Sex")+ theme(text = element_text(size = 10)) + ylim(0, 0.23) + geom_vline(xintercept=0.0833333, color = "red",linetype="dashed")
p <-ggplot(no_interaction, aes(x=maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y)
p8 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("Pollen")+ labs(x="MAF", y="Proportion", title="G")+ theme(text = element_text(size = 10)) + ylim(0, 0.23)+ geom_vline(xintercept=0.0778689, color = "red",linetype="dashed")
p7 + p8
```


```{r}
median(interaction$maf)
IQR(interaction$maf)
median(no_interaction$maf)
IQR(no_interaction$maf)

wilcox.test(interaction$maf, no_interaction$maf)
```


```{r}
g <- p_g_adj_01 %>% select(variant_id, af) %>% distinct() # 2950
gi <- p_gi_adj_01 %>% select(variant_id, af)  %>% distinct() # 233


no_interaction <-  g %>%
  anti_join(gi, by = "variant_id") # 2748

interaction <- inner_join(g, gi, by = c("variant_id","af")) # 241

interaction <- interaction %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))
no_interaction <- no_interaction %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))

p7 <- ggplot(interaction, aes(x=maf)) + geom_histogram(binwidth=0.01) + theme_classic() + ggtitle("G x Sex") + xlab("MAF")+ theme(text = element_text(size = 12))
p8 <- ggplot(no_interaction, aes(x=maf)) + geom_histogram(binwidth=0.01) + theme_classic() + ggtitle("G") + xlab("MAF")+ theme(text = element_text(size = 12))
p7 + p8
```

```{r}
median(interaction$maf)
IQR(interaction$maf)
median(no_interaction$maf)
IQR(no_interaction$maf)

wilcox.test(interaction$maf, no_interaction$maf)
```
