---
title: "no sex"
author: "Meng"
date: "2024-07-18"
output: html_document
---

```{r setup, include=FALSE}
library(arrow)
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyr)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/sex/"
```

# no interaction term
## permutation
```{r}
nosex_genes <- read.table(paste0(data, "nosex.cis_qtl.txt"), header = T) # 14755
hist(nosex_genes$pval_beta, nclass = 20)
# qval_nosex <- qvalue(nosex_genes$pval_beta)
# summary(qval_nosex)
# hist(qval_nosex)
nosex_egene <- nosex_genes %>% filter(qval < 0.1) # 9530

```


## get siginicant eQTLs without interaction
eQTLs significant for genotype term regarless of sex
```{r}
nosex_A1 <- read_parquet(paste0(data,"nosex.cis_qtl_pairs.1.parquet"))
nosex_A2 <- read_parquet(paste0(data,"nosex.cis_qtl_pairs.2.parquet"))
nosex_A3 <- read_parquet(paste0(data,"nosex.cis_qtl_pairs.3.parquet"))
nosex_A4 <- read_parquet(paste0(data,"nosex.cis_qtl_pairs.4.parquet"))

nosex_eqtl <- rbind(nosex_A1, nosex_A2, nosex_A3, nosex_A4) # 1368353
sum(nosex_genes$num_var) # 1368353

nosex_eqtl_full <- inner_join(nosex_eqtl, nosex_genes[,c(1,16:19)], by = "phenotype_id") # 1368353

nosex_eqtl_sig <- nosex_eqtl_full %>% filter(pval_nominal < pval_nominal_threshold) #  113056

length(unique(nosex_eqtl_sig$phenotype_id)) # 10134
length(unique(nosex_eqtl_sig$variant_id)) # 106621
```
## MAF
```{r}
# MAF
nosex_eqtl_sig <- nosex_eqtl_sig %>% mutate(maf = ifelse(af <= 0.5, af, 1 - af))
write.csv(nosex_eqtl_sig, file = paste0(data, "nosex_eqtl_sig.csv"), row.names = F, quote = F)

# unique
sex_eqtl_sig_af <- ML_eqtl_sig %>% select(variant_id, af, maf) %>% distinct()

# most sigificant
nosex_eqtl_sig_min <- nosex_eqtl_sig %>%
  group_by(phenotype_id) %>% 
  filter(pval_nominal == min(pval_nominal)) # 10784

write.table(nosex_eqtl_sig_min, file = paste0(data, "nosex_eqtl_sig_min.txt"), row.names = F, quote = F, sep = "\t")
```


# with interaction term
```{r}

```

