---
title: "LD_decay"
author: "Meng"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(patchwork)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/rumex_eqtl/plink/"
```

# LD decay

## A1
```{r}
# read in data
ld_bins <- read.table(paste0(data,"A1.ld_decay_bins_10_2"), header =T)

# plot LD decay
p1 <- ggplot(ld_bins, aes(distance, avg_R2)) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) + ggtitle("A1")+ xlim(0,1000)+theme_bw()
p1
```

## A2
```{r}
# read in data
ld_bins <- read.table(paste0(data,"A2.ld_decay_bins_10_2"), header =T)

# plot LD decay
p2 <- ggplot(ld_bins, aes(distance, avg_R2)) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) + ggtitle("A2")+ xlim(0,1000)+theme_bw()
p2
```

## A3
```{r}
# read in data
ld_bins <- read.table(paste0(data,"A3.ld_decay_bins_10_2"), header =T)

# plot LD decay
p3 <- ggplot(ld_bins, aes(distance, avg_R2)) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) + ggtitle("A3")+ xlim(0,1000)+theme_bw()
p3
```


## A4
```{r}
# read in data
ld_bins <- read.table(paste0(data,"A4.ld_decay_bins_10_2"), header =T)
#ggplot(ld_bins, aes(distance, avg_R2)) + geom_line() +xlab("Distance (bp)") + ylab(expression(italic(r)^2)) + ggtitle("A4") + xlim(0,1000)

# plot LD decay
p4 <- ggplot(ld_bins, aes(distance, avg_R2)) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) + ggtitle("A4") + xlim(0,1000)+theme_bw()
p4
```

```{r}
p1 + p2 + p3 + p4 + plot_layout(nrow=2)
```

```{r}
p1 + p2 + p3 + p4 + plot_layout(nrow=2)
```

```{r}
p1 + p2 + p3 + p4 + plot_layout(nrow=2)
```
```{r}
dfr <- read.delim(paste0(data,"A4.ld.summary"),sep="",header=F,check.names=F,stringsAsFactors=F)
colnames(dfr) <- c("dist","rsq")
dfr$distc <- cut(dfr$dist,breaks=seq(from=min(dfr$dist)-1,to=max(dfr$dist)+1,by=100000))
dfr1 <- dfr %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
dfr1 <- dfr1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")),
                        end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")),
                        mid=start+((end-start)/2))

ggplot()+
  geom_point(data=dfr1,aes(x=start,y=mean),size=0.4,colour="grey20")+
  geom_line(data=dfr1,aes(x=start,y=mean),size=0.3,alpha=0.5,colour="grey40")+
  labs(x="Distance (Megabases)",y=expression(LD~(r^{2})))+
  scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6),labels=c("0","2","4","6","8"))+
  theme_bw()
```
```{r}
dfr <- read.delim("A4.blocks.det",sep="",header=T,check.names=F,stringsAsFactors=F)
colnames(dfr) <- tolower(colnames(dfr))

# ld block density
p <- ggplot(dfr,aes(x=kb))+
  geom_density(size=0.5,colour="grey40")+
  labs(x="LD block length (Kb)",y="Density")+
  theme_bw()

```

number of SNPs
```{r}
59481369 + 40918717+26178124+19708237
```


